version: "2"

services:
  bot:
    build: .
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB_NAME=blockbot
    restart: unless-stopped
    
  postgres:
    image: postgres:16.2-alpine3.19
    environment:
      POSTGRES_DB: blockbot
      PGDATA: /var/lib/postgresql/data
    restart: unless-stopped
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: