services:
  bot:
    build: .
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      - POSTGRES_DB=blockbot
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password

  postgres:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=blockbot
      - POSTGRES_PASSWORD=password

volumes:
  postgres:
