name: Deploy

on:
  push:
  pull_request:
    types: [closed]

jobs:
  build:
    name: build
    uses: './.github/workflows/build.yml'
    if: github.event_name != 'pull_request'

  deploy_review:
    needs:
      - build

    runs-on: [self-hosted, deployment-runner]
    if: github.ref != 'refs/heads/main' && github.event_name == 'push'
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v7
      - name: Deploy review
        uses: docker://hashicorp/levant:0.3
        with:
          args: >-
            deploy
            -var=git_sha=${{ github.sha }}
            -var=environment_slug=${{ github.ref_name }}
            -address=http://nomad.service.consul:4646
            ./.github/deploy/review.hcl

  stop_review:
    runs-on: [self-hosted, deployment-runner]
    container:
      image: multani/nomad
    if: github.event_name == 'pull_request'
    timeout-minutes: 60
    steps:
      - run: nomad status -address=http://nomad.service.consul:4646
      - run: nomad job stop -address=http://nomad.service.consul:4646 -purge blockbot-${GITHUB_HEAD_REF}

  deploy_prod:
    needs:
      - build
    runs-on: [self-hosted, deployment-runner]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v7
      - name: Deploy production
        uses: docker://hashicorp/levant:0.3
        with:
          args: >-
            deploy
            -var=git_sha=${{ github.sha }}
            -address=http://nomad.service.consul:4646
            ./.github/deploy/production.hcl
